export const DEMO_ROOMS = [
  {
    id: 'enchanted_castle',
    label: 'Enchanted Castle',
    category: 'Fantasy',
    realSplatUrl: '/demo/enchanted_castle_like_room_world.spz',
    liteSplatUrl: '/demo/lite_enchanted_castle.ply',
    portalSplatUrl: '/demo/portal_enchanted_castle.ply',
    splatUrl: '/demo/lite_enchanted_castle.ply',
    colliderUrl: '/demo/enchanted_castle_like_room_collider.glb',
    floorPlanX: 190,
    floorPlanY: 245,
    floorPlanW: 170,
    floorPlanH: 130,
    realWidthM: 6.9,
    realDepthM: 5.8,
    worldX: 0,
    worldZ: 0,
    format: 'spz',
    visualFormat: 'ply',
    visualFlipX: false,
    footprint: {
      xMin: -3.543,
      xMax: 3.443,
      zMin: -1.844,
      zMax: 4.008,
    },
    stitchDoors: {
      entry: { wall: 'west', x: -3.543, z: -1.064, width: 1.3 },
      exit: { wall: 'east', x: 3.443, z: -1.064, width: 1.3 },
    },
    portalCut: {
      heightM: 2.35,
    },
    demoMeta: {
      numPoints: 500000,
      fractionalBits: 12,
      splatFloorY: -2.992,
      splatCeilY: 0.588,
      splatYLift: 2.992,
      colliderYLift: 2.953,
    },
  },
  {
    id: 'hogwarts_bedroom',
    label: 'Magical Bedroom',
    category: 'Real Estate',
    realSplatUrl: '/demo/Hogwarts_Castle_Magical_Bedroom.spz',
    liteSplatUrl: '/demo/lite_hogwarts_bedroom.ply',
    portalSplatUrl: '/demo/portal_hogwarts_bedroom.ply',
    splatUrl: '/demo/lite_hogwarts_bedroom.ply',
    colliderUrl: '/demo/Hogwarts_Castle_Magical_Bedroom_collider.glb',
    floorPlanX: 475,
    floorPlanY: 245,
    floorPlanW: 185,
    floorPlanH: 150,
    realWidthM: 7.4,
    realDepthM: 5.8,
    worldX: 9.64,
    worldZ: 0,
    format: 'spz',
    visualFormat: 'ply',
    visualFlipX: false,
    footprint: {
      xMin: -5.347,
      xMax: 6.346,
      zMin: -6.848,
      zMax: 6.257,
    },
    stitchDoors: {
      entry: { wall: 'west', x: -5.347, z: -1.064, width: 1.4 },
      exit: { wall: 'east', x: 6.346, z: -1.064, width: 1.4 },
    },
    portalCut: {
      heightM: 2.35,
    },
    demoMeta: {
      numPoints: 2000000,
      fractionalBits: 10,
      splatFloorY: -0.005,
      splatCeilY: 4.023,
      splatYLift: 0.005,
      colliderYLift: -0.029,
    },
  },
  {
    id: 'cramped_apartment',
    label: 'Cramped Apartment',
    category: 'Horror',
    realSplatUrl: '/demo/Cramped_Urban_Apartment_Night.spz',
    liteSplatUrl: '/demo/lite_cramped_apartment.ply',
    portalSplatUrl: '/demo/portal_cramped_apartment.ply',
    splatUrl: '/demo/lite_cramped_apartment.ply',
    colliderUrl: '/demo/Cramped_Urban_Apartment_Night_collider.glb',
    floorPlanX: 760,
    floorPlanY: 245,
    floorPlanW: 220,
    floorPlanH: 165,
    realWidthM: 8.8,
    realDepthM: 6.6,
    worldX: 27.587,
    worldZ: 0,
    format: 'spz',
    visualFormat: 'ply',
    visualFlipX: false,
    footprint: {
      xMin: -10.082,
      xMax: 3.722,
      zMin: -12.528,
      zMax: 2.394,
    },
    stitchDoors: {
      entry: { wall: 'west', x: -10.082, z: -1.064, width: 1.25 },
      exit: { wall: 'east', x: 3.722, z: -1.064, width: 1.25 },
    },
    portalCut: {
      heightM: 2.3,
    },
    demoMeta: {
      numPoints: 2000000,
      fractionalBits: 10,
      splatFloorY: -1.302,
      splatCeilY: 4.176,
      splatYLift: 1.302,
      colliderYLift: 3.828,
    },
  },
  {
    id: 'cozy_bedroom',
    label: 'Cozy Bedroom',
    category: 'Fresh Upload',
    realSplatUrl: '/demo/cozy_dimly_lit_bedroom.spz',
    liteSplatUrl: '/demo/lite_cozy_bedroom.ply',
    portalSplatUrl: '/demo/portal_cozy_bedroom.ply',
    splatUrl: '/demo/lite_cozy_bedroom.ply',
    colliderUrl: '/demo/cozy_dimly_lit_bedroom_collider.glb',
    floorPlanX: 1045,
    floorPlanY: 245,
    floorPlanW: 180,
    floorPlanH: 135,
    realWidthM: 7.2,
    realDepthM: 5.4,
    worldX: 39.5,
    worldZ: 0,
    format: 'spz',
    visualFormat: 'ply',
    visualFlipX: false,
    footprint: {
      xMin: -3.175,
      xMax: 4.698,
      zMin: -2.869,
      zMax: 3.009,
    },
    stitchDoors: {
      entry: { wall: 'west', x: -3.175, z: -1.064, width: 1.2 },
      exit: { wall: 'east', x: 4.698, z: -1.064, width: 1.2 },
    },
    portalCut: {
      heightM: 2.25,
    },
    demoMeta: {
      numPoints: 1920000,
      fractionalBits: 10,
      splatFloorY: -0.027,
      splatCeilY: 2.826,
      splatYLift: 0.027,
      colliderYLift: 0.014,
    },
  },
];

export function makeEmptyRoom(index) {
  const id = `room_${Date.now()}_${index}`;
  return {
    id,
    label: `Room ${index + 1}`,
    category: 'Custom',
    floorPlanX: 180 + index * 220,
    floorPlanY: 240,
    floorPlanW: 160,
    floorPlanH: 120,
    realWidthM: 4,
    realDepthM: 3,
    format: 'pending',
    visualFormat: 'pending',
    visualFlipX: false,
  };
}
