export const LUXURY_PENTHOUSE_PLAN = {
  id: 'luxury_penthouse_plan',
  label: 'Luxury Penthouse Plan',
  url: '/plans/luxury-penthouse-floorplan.png',
  width: 1220,
  height: 858,
  metersPerPixel: 0.018,
};

export const LUXURY_PENTHOUSE_ROOMS = [
  {
    id: 'penthouse_living_dining',
    label: 'Living & Dining',
    category: 'Primary Space',
    realSplatUrl: '/environments/Grand Luxury Penthouse Living Room.spz',
    liteSplatUrl: '/environments/lite_grand_luxury_penthouse_living_room.ply',
    portalSplatUrl: '/environments/portal_grand_luxury_penthouse_living_room.ply',
    splatUrl: '/environments/lite_grand_luxury_penthouse_living_room.ply',
    colliderUrl: '/environments/Grand Luxury Penthouse Living Room_collider.glb',
    floorPlanX: 405,
    floorPlanY: 475,
    floorPlanW: 300,
    floorPlanH: 410,
    realWidthM: 10.98,
    realDepthM: 4.65,
    format: 'spz',
    visualFormat: 'ply',
    footprint: {
      xMin: -20.194,
      xMax: 5.495,
      zMin: -13.367,
      zMax: 7.791,
    },
    stitchDoors: {
      entry: { wall: 'west', x: -20.194, z: 0, width: 1.55 },
      exit: { wall: 'east', x: 5.495, z: 0, width: 1.55 },
    },
    portalDoors: {
      guest_suite: { wall: 'west', x: -20.194, z: -1.6, width: 1.35, label: 'Bedroom 4' },
      bedroom_two: { wall: 'east', x: 5.495, z: -0.65, width: 1.25, label: 'Bedroom 2' },
    },
    portalCut: {
      heightM: 2.4,
      planeMarginM: 0.9,
    },
    demoMeta: {
      numPoints: 3840000,
      fractionalBits: 10,
      splatFloorY: -0.015,
      splatCeilY: 3.354,
      splatYLift: 0.015,
      colliderYLift: 0.002,
    },
  },
  {
    id: 'penthouse_guest_suite',
    label: 'Bedroom 4 Guest Suite',
    category: 'Bedroom',
    realSplatUrl: '/environments/Luxury guest suite, evening ambiance.spz',
    liteSplatUrl: '/environments/lite_luxury_guest_suite_evening_ambiance.ply',
    portalSplatUrl: '/environments/portal_luxury_guest_suite_evening_ambiance.ply',
    splatUrl: '/environments/lite_luxury_guest_suite_evening_ambiance.ply',
    colliderUrl: '/environments/Luxury guest suite, evening ambiance_collider.glb',
    floorPlanX: 205,
    floorPlanY: 335,
    floorPlanW: 165,
    floorPlanH: 205,
    realWidthM: 4.12,
    realDepthM: 4.42,
    format: 'spz',
    visualFormat: 'ply',
    footprint: {
      xMin: -4.781,
      xMax: 3.907,
      zMin: -7.633,
      zMax: 2.465,
    },
    stitchDoors: {
      entry: { wall: 'west', x: -4.781, z: -0.8, width: 1.25 },
      exit: { wall: 'east', x: 3.907, z: -0.8, width: 1.25 },
    },
    portalDoors: {
      living: { wall: 'east', x: 3.907, z: -0.8, width: 1.25, label: 'Living & Dining' },
    },
    portalCut: {
      heightM: 2.3,
    },
    demoMeta: {
      numPoints: 1920000,
      fractionalBits: 10,
      splatFloorY: -0.006,
      splatCeilY: 3.143,
      splatYLift: 0.006,
      colliderYLift: -0.05,
    },
  },
  {
    id: 'penthouse_bedroom_two',
    label: 'Bedroom 2',
    category: 'Bedroom',
    realSplatUrl: '/environments/Luxury Contemporary Bedroom Interior.spz',
    liteSplatUrl: '/environments/lite_luxury_contemporary_bedroom_interior.ply',
    portalSplatUrl: '/environments/portal_luxury_contemporary_bedroom_interior.ply',
    splatUrl: '/environments/lite_luxury_contemporary_bedroom_interior.ply',
    colliderUrl: '/environments/Luxury Contemporary Bedroom Interior_collider.glb',
    floorPlanX: 735,
    floorPlanY: 335,
    floorPlanW: 135,
    floorPlanH: 190,
    realWidthM: 3.65,
    realDepthM: 4.87,
    format: 'spz',
    visualFormat: 'ply',
    footprint: {
      xMin: -2.981,
      xMax: 3.136,
      zMin: -7.207,
      zMax: 1.644,
    },
    stitchDoors: {
      entry: { wall: 'west', x: -2.981, z: -0.75, width: 1.2 },
      exit: { wall: 'east', x: 3.136, z: -0.75, width: 1.2 },
    },
    portalDoors: {
      living: { wall: 'west', x: -2.981, z: -0.75, width: 1.2, label: 'Living & Dining' },
      master_suite: { wall: 'east', x: 3.136, z: -0.75, width: 1.2, label: 'Master Bedroom' },
    },
    portalCut: {
      heightM: 2.25,
    },
    demoMeta: {
      numPoints: 1920000,
      fractionalBits: 10,
      splatFloorY: 0.005,
      splatCeilY: 3.045,
      splatYLift: -0.005,
      colliderYLift: -0.048,
    },
  },
  {
    id: 'penthouse_master_suite',
    label: 'Master Bedroom Suite',
    category: 'Bedroom',
    realSplatUrl: '/environments/Luxury Penthouse Master Bedroom Suite.spz',
    liteSplatUrl: '/environments/lite_luxury_penthouse_master_bedroom_suite.ply',
    portalSplatUrl: '/environments/portal_luxury_penthouse_master_bedroom_suite.ply',
    splatUrl: '/environments/lite_luxury_penthouse_master_bedroom_suite.ply',
    colliderUrl: '/environments/Luxury Penthouse Master Bedroom Suite_collider.glb',
    floorPlanX: 895,
    floorPlanY: 330,
    floorPlanW: 170,
    floorPlanH: 195,
    realWidthM: 4.27,
    realDepthM: 4.57,
    format: 'spz',
    visualFormat: 'ply',
    footprint: {
      xMin: -5.023,
      xMax: 4.586,
      zMin: -10.054,
      zMax: 6.771,
    },
    stitchDoors: {
      entry: { wall: 'west', x: -5.023, z: -0.9, width: 1.35 },
      exit: { wall: 'east', x: 4.586, z: -0.9, width: 1.35 },
    },
    portalDoors: {
      bedroom_two: { wall: 'west', x: -5.023, z: -0.9, width: 1.35, label: 'Bedroom 2' },
      dressing: { wall: 'east', x: 4.586, z: -0.9, width: 1.2, label: 'Dressing' },
    },
    portalCut: {
      heightM: 2.35,
    },
    demoMeta: {
      numPoints: 1920000,
      fractionalBits: 10,
      splatFloorY: -0.007,
      splatCeilY: 3.201,
      splatYLift: 0.007,
      colliderYLift: -0.024,
    },
  },
  {
    id: 'penthouse_dressing_room',
    label: 'Master Dressing',
    category: 'Wardrobe',
    realSplatUrl: '/environments/Luxurious Master Dressing Room.spz',
    liteSplatUrl: '/environments/lite_luxurious_master_dressing_room.ply',
    portalSplatUrl: '/environments/portal_luxurious_master_dressing_room.ply',
    splatUrl: '/environments/lite_luxurious_master_dressing_room.ply',
    colliderUrl: '/environments/Luxurious Master Dressing Room_collider.glb',
    floorPlanX: 930,
    floorPlanY: 505,
    floorPlanW: 115,
    floorPlanH: 120,
    realWidthM: 2.6,
    realDepthM: 2.2,
    format: 'spz',
    visualFormat: 'ply',
    footprint: {
      xMin: -6.039,
      xMax: 2.441,
      zMin: -7.238,
      zMax: 6.416,
    },
    stitchDoors: {
      entry: { wall: 'west', x: -6.039, z: -0.65, width: 1.15 },
      exit: { wall: 'east', x: 2.441, z: -0.65, width: 1.15 },
    },
    portalDoors: {
      master_suite: { wall: 'west', x: -6.039, z: -0.65, width: 1.15, label: 'Master Bedroom' },
      spa_bathroom: { wall: 'east', x: 2.441, z: -0.65, width: 1.1, label: 'Bathroom' },
    },
    portalCut: {
      heightM: 2.25,
    },
    demoMeta: {
      numPoints: 1920000,
      fractionalBits: 10,
      splatFloorY: -0.002,
      splatCeilY: 3.004,
      splatYLift: 0.002,
      colliderYLift: -0.011,
    },
  },
  {
    id: 'penthouse_spa_bathroom',
    label: 'Spa Master Bathroom',
    category: 'Bathroom',
    realSplatUrl: '/environments/Luxury Spa Master Bathroom.spz',
    liteSplatUrl: '/environments/lite_luxury_spa_master_bathroom.ply',
    portalSplatUrl: '/environments/portal_luxury_spa_master_bathroom.ply',
    splatUrl: '/environments/lite_luxury_spa_master_bathroom.ply',
    colliderUrl: '/environments/Luxury Spa Master Bathroom_collider.glb',
    floorPlanX: 1035,
    floorPlanY: 500,
    floorPlanW: 120,
    floorPlanH: 125,
    realWidthM: 2.6,
    realDepthM: 2.21,
    format: 'spz',
    visualFormat: 'ply',
    footprint: {
      xMin: -2.343,
      xMax: 3.04,
      zMin: -4.997,
      zMax: 9.713,
    },
    stitchDoors: {
      entry: { wall: 'west', x: -2.343, z: 0.2, width: 1.1 },
      exit: { wall: 'east', x: 3.04, z: 0.2, width: 1.1 },
    },
    portalDoors: {
      dressing: { wall: 'west', x: -2.343, z: 0.2, width: 1.1, label: 'Dressing' },
    },
    portalCut: {
      heightM: 2.2,
    },
    demoMeta: {
      numPoints: 1920000,
      fractionalBits: 10,
      splatFloorY: -0.007,
      splatCeilY: 2.906,
      splatYLift: 0.007,
      colliderYLift: -0.002,
    },
  },
];

export const LUXURY_PENTHOUSE_PORTAL_LINKS = [
  {
    id: 'living_to_guest_suite',
    from: 'penthouse_living_dining',
    fromDoor: 'guest_suite',
    to: 'penthouse_guest_suite',
    toDoor: 'living',
    label: 'Living & Dining to Bedroom 4',
  },
  {
    id: 'living_to_bedroom_two',
    from: 'penthouse_living_dining',
    fromDoor: 'bedroom_two',
    to: 'penthouse_bedroom_two',
    toDoor: 'living',
    label: 'Living & Dining to Bedroom 2',
  },
  {
    id: 'bedroom_two_to_master',
    from: 'penthouse_bedroom_two',
    fromDoor: 'master_suite',
    to: 'penthouse_master_suite',
    toDoor: 'bedroom_two',
    label: 'Bedroom 2 to Master Bedroom',
  },
  {
    id: 'master_to_dressing',
    from: 'penthouse_master_suite',
    fromDoor: 'dressing',
    to: 'penthouse_dressing_room',
    toDoor: 'master_suite',
    label: 'Master Bedroom to Dressing',
  },
  {
    id: 'dressing_to_spa',
    from: 'penthouse_dressing_room',
    fromDoor: 'spa_bathroom',
    to: 'penthouse_spa_bathroom',
    toDoor: 'dressing',
    label: 'Dressing to Bathroom',
  },
];

export const PROPERTY_PRESETS = [
  {
    id: 'luxury_penthouse',
    label: 'Luxury Penthouse',
    plan: LUXURY_PENTHOUSE_PLAN,
    rooms: LUXURY_PENTHOUSE_ROOMS,
    portalLinks: LUXURY_PENTHOUSE_PORTAL_LINKS,
  },
];
